# Generated by Django 3.2.21 on 2023-10-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_totpprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOTPProfile',
        ),
    ]
